# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
    config.vm.define "controller" do |controller|
        controller.vm.box = "centos/7"
        controller.vm.hostname ="controller"
        controller.vm.network "private_network", ip: "192.168.33.10"
        controller.vm.provision :shell, path: "installing_ansible.bash"
    end
    config.vm.define "worker" do |worker|
        worker.vm.box =  "centos/7"
        worker.vm.hostname = "worker"
        worker.vm.network "private_network", ip: "192.168.33.11"
    end
end
